[build]
buildCommand = "python manage.py collectstatic --no-input"

[deploy]
preDeployCommand = "python manage.py migrate --no-input"
startCommand = "gunicorn core.wsgi:application --workers 2 --threads 2 --worker-class gthread --timeout 120 --max-requests 1000 --bind 0.0.0.0:$PORT"
