# Generated by Django 6.0.3 on 2026-04-08 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitlistentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Cadastrado em'),
        ),
    ]
