# Generated by Django 6.0.3 on 2026-04-08 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_alter_waitlistentry_created_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WaitlistEntry',
            new_name='ListaDeEspera',
        ),
        migrations.AlterModelOptions(
            name='listadeespera',
            options={'ordering': ['-created_at'], 'verbose_name': 'Registro Lista de Espera', 'verbose_name_plural': 'Registros Lista de Espera'},
        ),
    ]
