# Generated by Django 6.0.3 on 2026-04-08 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_rename_waitlistentry_listadeespera_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ListaDeEspera',
            new_name='WaitlistEntry',
        ),
        migrations.AlterModelOptions(
            name='waitlistentry',
            options={'ordering': ['-created_at'], 'verbose_name': 'Registro Waitlist', 'verbose_name_plural': 'Registros Waitlist'},
        ),
    ]
