# Generated by Django 6.0.4 on 2026-04-16 13:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del cliente')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono')),
                ('company', models.CharField(blank=True, max_length=255, null=True, verbose_name='Empresa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL, verbose_name='Propietario')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integration_type', models.CharField(choices=[('google_ads', 'Google Ads'), ('ga4', 'Google Analytics 4')], max_length=50, verbose_name='Tipo de integración')),
                ('status', models.CharField(choices=[('connected', 'Conectado'), ('disconnected', 'Desconectado'), ('action_required', 'Acción Necesaria')], default='disconnected', max_length=50, verbose_name='Estado')),
                ('access_token', models.TextField(blank=True, null=True)),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
                ('google_ads_customer_id', models.CharField(blank=True, max_length=50, null=True)),
                ('ga4_property_id', models.CharField(blank=True, max_length=50, null=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_integrations', to='reportai.client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': '[DEPRECATED] Integración de Cliente',
                'verbose_name_plural': '[DEPRECATED] Integraciones de Clientes',
            },
        ),
        migrations.CreateModel(
            name='IntegrationAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('google_ads', 'Google Ads'), ('ga4', 'Google Analytics 4'), ('meta_ads', 'Meta Ads (Facebook/Instagram)')], max_length=50, verbose_name='Canal')),
                ('account_id', models.CharField(help_text="ID externo de la cuenta (ej: '123-456-7890' para Google Ads)", max_length=100, verbose_name='ID de la Cuenta')),
                ('account_name', models.CharField(blank=True, help_text="Nombre amigable para mostrar en la UI (ej: 'Marca X - Search')", max_length=255, null=True, verbose_name='Nombre de la Cuenta')),
                ('status', models.CharField(choices=[('connected', 'Conectado'), ('disconnected', 'Desconectado'), ('pending_selection', 'Pendiente de Selección'), ('token_expired', 'Token Expirado'), ('error', 'Error')], default='disconnected', max_length=50, verbose_name='Estado')),
                ('access_token', models.TextField(blank=True, null=True, verbose_name='Access Token')),
                ('refresh_token', models.TextField(blank=True, null=True, verbose_name='Refresh Token')),
                ('token_expiry', models.DateTimeField(blank=True, null=True, verbose_name='Expiración del token')),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='Datos específicos del canal en formato JSON', verbose_name='Datos Adicionales')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='Última sincronización')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='reportai.client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Cuenta de Integración',
                'verbose_name_plural': 'Cuentas de Integración',
                'ordering': ['client', 'channel', 'account_name'],
                'unique_together': {('client', 'channel', 'account_id')},
            },
        ),
        migrations.CreateModel(
            name='SelectedCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('campaign_id', models.CharField(help_text='ID externo de la campaña', max_length=100, verbose_name='ID de la Campaña')),
                ('campaign_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre de la Campaña')),
                ('campaign_type', models.CharField(blank=True, help_text="Ej: 'SEARCH', 'DISPLAY', 'SHOPPING', 'VIDEO'", max_length=100, null=True, verbose_name='Tipo de Campaña')),
                ('is_active', models.BooleanField(default=True, help_text='Si está activa, se incluirá en los reportes', verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_campaigns', to='reportai.integrationaccount', verbose_name='Cuenta de Integración')),
            ],
            options={
                'verbose_name': 'Campaña Seleccionada',
                'verbose_name_plural': 'Campañas Seleccionadas',
                'ordering': ['campaign_name'],
                'unique_together': {('integration', 'campaign_id')},
            },
        ),
        migrations.CreateModel(
            name='SelectedMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_key', models.CharField(max_length=100, verbose_name='Clave de la métrica')),
                ('metric_name', models.CharField(max_length=255, verbose_name='Nombre de la métrica')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Orden de visualización')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('integration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_metrics', to='reportai.integrationaccount', verbose_name='Cuenta de Integración')),
            ],
            options={
                'verbose_name': 'Métrica Seleccionada',
                'verbose_name_plural': 'Métricas Seleccionadas',
                'ordering': ['display_order', 'metric_key'],
                'unique_together': {('integration', 'metric_key')},
            },
        ),
    ]
