# Generated by Django 6.0.4 on 2026-04-15 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del cliente')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono')),
                ('company', models.CharField(blank=True, max_length=255, null=True, verbose_name='Empresa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL, verbose_name='Propietario')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integration_type', models.CharField(choices=[('google_ads', 'Google Ads'), ('ga4', 'Google Analytics 4')], max_length=50, verbose_name='Tipo de integración')),
                ('status', models.CharField(choices=[('connected', 'Conectado'), ('disconnected', 'Desconectado'), ('action_required', 'Acción Necesaria')], default='disconnected', max_length=50, verbose_name='Estado')),
                ('access_token', models.TextField(blank=True, null=True, verbose_name='Access Token')),
                ('refresh_token', models.TextField(blank=True, null=True, verbose_name='Refresh Token')),
                ('token_expiry', models.DateTimeField(blank=True, null=True, verbose_name='Expiración del token')),
                ('google_ads_customer_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Google Ads Customer ID')),
                ('ga4_property_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='GA4 Property ID')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='Última sincronización')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='reportai.client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Integración de Cliente',
                'verbose_name_plural': 'Integraciones de Clientes',
                'unique_together': {('client', 'integration_type')},
            },
        ),
        migrations.CreateModel(
            name='SelectedMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_key', models.CharField(max_length=100, verbose_name='Clave de la métrica')),
                ('metric_name', models.CharField(max_length=255, verbose_name='Nombre de la métrica')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_metrics', to='reportai.clientintegration', verbose_name='Integración')),
            ],
            options={
                'verbose_name': 'Métrica Seleccionada',
                'verbose_name_plural': 'Métricas Seleccionadas',
                'unique_together': {('integration', 'metric_key')},
            },
        ),
    ]
