# Generated by Django 6.0.4 on 2026-04-27 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportai', '0002_integrationaccount_customer_hierarchy'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='knowledge_level',
            field=models.CharField(choices=[('leigo', 'Leigo (lenguaje de negocio)'), ('avancado', 'Avanzado (términos técnicos)')], default='leigo', help_text='Define el tono del mensaje generado por la IA', max_length=10, verbose_name='Nivel de conocimiento'),
        ),
        migrations.AddField(
            model_name='client',
            name='next_report_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Próximo envío'),
        ),
        migrations.AddField(
            model_name='client',
            name='report_frequency_days',
            field=models.IntegerField(default=7, help_text='7 = semanal, 14 = quincenal, 30 = mensual', verbose_name='Frecuencia (días)'),
        ),
        migrations.AddField(
            model_name='client',
            name='send_channel',
            field=models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('both', 'Email + WhatsApp')], default='email', max_length=10, verbose_name='Canal de envío'),
        ),
        migrations.CreateModel(
            name='ReportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_generated', models.TextField(verbose_name='Mensaje generado')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('channel_used', models.CharField(max_length=10, verbose_name='Canal usado')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Enviado'), ('failed', 'Fallido'), ('partial', 'Enviado parcialmente')], default='pending', max_length=10, verbose_name='Estado')),
                ('email_status', models.CharField(blank=True, choices=[('pending', 'Pendiente'), ('sent', 'Enviado'), ('failed', 'Fallido'), ('partial', 'Enviado parcialmente')], max_length=10, null=True, verbose_name='Estado email')),
                ('whatsapp_status', models.CharField(blank=True, choices=[('pending', 'Pendiente'), ('sent', 'Enviado'), ('failed', 'Fallido'), ('partial', 'Enviado parcialmente')], max_length=10, null=True, verbose_name='Estado WhatsApp')),
                ('error_detail', models.TextField(blank=True, null=True, verbose_name='Detalle del error')),
                ('metrics_snapshot', models.JSONField(blank=True, default=dict, verbose_name='Snapshot de métricas')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_logs', to='reportai.client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Log de Reporte',
                'verbose_name_plural': 'Logs de Reportes',
                'ordering': ['-sent_at'],
            },
        ),
    ]
