# Generated by Django 6.0.4 on 2026-05-06 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportai', '0006_clientmetricconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='report_frequency',
            field=models.CharField(blank=True, choices=[('weekly', 'Semanal'), ('biweekly', 'Quincenal'), ('monthly', 'Mensual'), ('quarterly', 'Trimestral')], default='weekly', max_length=20, null=True, verbose_name='Frecuencia de envío'),
        ),
        migrations.AddField(
            model_name='client',
            name='report_send_day',
            field=models.IntegerField(blank=True, choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], default=0, help_text='Día de envío: 0=Lunes...6=Domingo (mensual/trimestral: día del mes 1-28)', null=True, verbose_name='Día de envío'),
        ),
    ]
