# Generated by Django 6.0.4 on 2026-05-07 01:08

import django.db.models.deletion
from django.db import migrations, models
from django.utils.text import slugify


def populate_dashboard_slugs(apps, schema_editor):
    """Preenche dashboard_slug para clientes já existentes antes de criar o índice único."""
    Client = apps.get_model('reportai', 'Client')
    for client in Client.objects.all():
        base = slugify(client.name) or 'cliente'
        short_id = str(client.dashboard_token)[:4]
        client.dashboard_slug = f"{base}-{short_id}"
        client.save(update_fields=['dashboard_slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('reportai', '0007_client_report_frequency_client_report_send_day'),
    ]

    operations = [
        # 1. Adicionar o campo sem unique para permitir que todos os registros existentes
        #    recebam valor antes da constraint ser criada
        migrations.AddField(
            model_name='client',
            name='dashboard_slug',
            field=models.CharField(blank=True, max_length=80, default='', verbose_name='Slug del dashboard'),
        ),
        # 2. Preencher slugs em todos os registros existentes
        migrations.RunPython(populate_dashboard_slugs, migrations.RunPython.noop),
        # 3. Adicionar o índice unique agora que todos os valores são distintos
        migrations.AlterField(
            model_name='client',
            name='dashboard_slug',
            field=models.CharField(blank=True, max_length=80, unique=True, verbose_name='Slug del dashboard'),
        ),
        migrations.AddField(
            model_name='clientmetricconfig',
            name='is_highlight',
            field=models.BooleanField(default=False, verbose_name='Destaque en el dashboard'),
        ),
        migrations.CreateModel(
            name='TimelineEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('badge_type', models.CharField(choices=[('resultado', 'Resultado'), ('actualizacion', 'Actualización'), ('marco', 'Marco'), ('reunion', 'Reunión'), ('otro', 'Otro')], default='actualizacion', max_length=20, verbose_name='Tipo de badge')),
                ('badge_color', models.CharField(choices=[('blue', 'Azul'), ('green', 'Verde'), ('yellow', 'Amarillo'), ('red', 'Rojo'), ('purple', 'Morado'), ('gray', 'Gris')], default='blue', max_length=10, verbose_name='Color del badge')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_entries', to='reportai.client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Entrada de Timeline',
                'verbose_name_plural': 'Entradas de Timeline',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
