# Generated by Django 6.0.4 on 2026-05-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportai', '0008_dashboard_slug_is_highlight_timeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportlog',
            name='dashboard_insight',
            field=models.TextField(blank=True, default='', verbose_name='Insight del dashboard'),
        ),
    ]
