# Generated by Django 6.0.4 on 2026-05-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportai', '0010_agencyprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencyprofile',
            name='dpa_accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Aceite do DPA em'),
        ),
        migrations.AddField(
            model_name='agencyprofile',
            name='legal_version',
            field=models.CharField(default='1.0', max_length=20, verbose_name='Versão dos documentos legais aceitos'),
        ),
        migrations.AddField(
            model_name='agencyprofile',
            name='privacy_accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Aceite da Privacidade em'),
        ),
        migrations.AddField(
            model_name='agencyprofile',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Aceite dos Termos em'),
        ),
    ]
