# Generated by Django 6.0.4 on 2026-05-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportai', '0012_enable_rls_security'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencyprofile',
            name='trial_notes',
            field=models.TextField(blank=True, default='', help_text='Observaciones manuales de seguimiento', verbose_name='Notas del trial'),
        ),
        migrations.AddField(
            model_name='agencyprofile',
            name='trial_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inicio del trial'),
        ),
        migrations.AddField(
            model_name='agencyprofile',
            name='trial_status',
            field=models.CharField(choices=[('active', 'Activo'), ('cancelled', 'Cancelado')], default='active', max_length=20, verbose_name='Estado del trial'),
        ),
    ]
